CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INT NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'usd',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);